name: hermes
x-common-vars: &var
  tty: true
  stdin_open: true
  privileged: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s

x-common-env: &env
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
  ROS_DOMAIN_ID: $ROS_DOMAIN_ID

services:
  mavros:
    build:
      context: ../..
      dockerfile: docker/dockerfiles/Dockerfile
      target: mavros
      args:
        USER: mavros
        USER_UID: ${UID}
        USER_GID: ${GID}
    image: hermes/mavros:dev
    container_name: mavros
    <<: *var
    group_add: ["dialout","plugdev"]
    # devices:
    #   - ${PX4_DEV:-/dev/ttyACM0}:${PX4_DEV:-/dev/ttyACM0}
    environment:
      <<: *env
    volumes:
      - ../../packages/mavros_pkg:/home/mavros/hermes_ws/src
      - type: volume
        source: mavros_install
        target: /home/mavros/hermes_ws/install
      - type: volume
        source: mavros_build
        target: /home/mavros/hermes_ws/build
    command: bash

  slam:
    build:
      context: ../..
      dockerfile: docker/dockerfiles/Dockerfile
      target: slam
      args:
        USER: slam
        USER_UID: ${UID}
        USER_GID: ${GID}
    image: hermes/slam:dev
    container_name: slam
    <<: *var
    group_add: ["video"]
    environment:
      <<: *env
    volumes:
      - ../../packages/slam_pkg:/home/slam/hermes_ws/src
      - type: volume
        source: slam_install
        target: /home/slam/hermes_ws/install
      - type: volume
        source: slam_build
        target: /home/slam/hermes_ws/build
    command: bash

volumes:
  mavros_install: {}
  mavros_build: {}
  slam_install: {}
  slam_build: {}